name: Deploy App Using Username and Password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to Server using SSH with password
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/jobin/test || exit 1

          echo "--- Git Info ---"
          git status
          git fetch origin
          git checkout main
          git reset --hard origin/main

          echo "--- Installing dependencies ---"
          npm install

          echo "--- Restarting PM2 ---"
          pm2 restart app || pm2 start app.js --name app
        EOF
