- name: Deploy to Server using SSH with password
  run: |
    sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
      cd /home/jobin/test || exit 1

      echo "✅ Marking directory as safe"
      git config --global --add safe.directory /home/jobin/test

      echo "📥 Pulling latest code"
      git fetch origin
      git checkout main
      git reset --hard origin/main

      echo "📦 Installing dependencies"
      npm install

      echo "🚀 Restarting PM2 app"
      pm2 restart app || pm2 start app.js --name app

      echo "✅ Deployment done"
    EOF
